- hosts: localhost
  connection: local
  vars:
    - appliancelist: "{{ groups['sns-appliances'] }}"

  gather_facts: true

  tasks:
    - include: creation_tunnel_ipsec-task.yaml target="{{ item }}"
      with_items: "{{ appliancelist }}"
